# LoggedFS-python
# Filesystem monitoring with Fuse and Python
# https://github.com/pleiszenburg/loggedfs-python
#
#	.travis.yml: Configuration for Travis CI build test
#
# 	Copyright (C) 2017 Sebastian M. Ernst <ernst@pleiszenburg.de>
#
# <LICENSE_BLOCK>
# The contents of this file are subject to the Apache License
# Version 2 ("License"). You may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# https://www.apache.org/licenses/LICENSE-2.0
# https://github.com/pleiszenburg/loggedfs-python/blob/master/LICENSE
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
# specific language governing rights and limitations under the License.
# </LICENSE_BLOCK>


# Check this file at:
# http://lint.travis-ci.org/

# A virtual machine IS required for loading FUSE kernel module:
# https://github.com/travis-ci/travis-ci/issues/1100#issuecomment-160169121
sudo: required

# Go for more 'recent' version of Ubuntu
dist: trusty

# Repository language
language: python

# Python version
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Install dependencies
addons:
  apt:
    packages:
    - fuse
    - libfuse2
    - libfuse-dev

# Get debug output
before_install:
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - sudo echo "user_allow_other" | sudo tee /etc/fuse.conf > /dev/null
  - python --version
  - uname -a

# command to install dependencies and module
install: make install

# command to run tests
script: make test

# Notify developers
notifications:
  email:
    recipients:
      - ernst@pleiszenburg.de
    on_success: always
    on_failure: always
